/**
 * Generates `src/sanity/schemas/documents/siteCopy.ts` from the Spanish
 * dictionary, so the Studio always mirrors the shape of `src/config/dictionaries/es.ts`.
 *
 * Add a key to es.ts (and en.ts), re-run `npm run sanity:gen-copy`, and the
 * Studio picks up the new field. Hand-editing the generated file is pointless —
 * it is overwritten on every run.
 *
 *   npm run sanity:gen-copy
 */
import { writeFileSync } from 'node:fs';
import { es } from '../src/config/dictionaries/es';

const OUT = 'src/sanity/schemas/documents/siteCopy.ts';

/** Long copy gets a textarea instead of a single-line input. */
const TEXT_THRESHOLD = 80;

function titleCase(key: string): string {
  const spaced = key.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/[_-]+/g, ' ');
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function indent(depth: number): string {
  return '  '.repeat(depth);
}

/** Emit a `defineField`/plain field literal for one dictionary value. */
function fieldFor(key: string, value: unknown, depth: number): string {
  const pad = indent(depth);
  const title = quote(titleCase(key));

  if (typeof value === 'string') {
    const type = value.length > TEXT_THRESHOLD ? 'localeText' : 'localeString';
    return `${pad}{ name: ${quote(key)}, title: ${title}, type: '${type}' },`;
  }

  if (Array.isArray(value)) {
    const first = value[0];
    if (typeof first === 'string') {
      return `${pad}{ name: ${quote(key)}, title: ${title}, type: 'array', of: [{ type: 'localeString' }] },`;
    }
    if (first && typeof first === 'object') {
      const inner = Object.entries(first as Record<string, unknown>)
        .map(([k, v]) => fieldFor(k, v, depth + 3))
        .join('\n');
      const previewKey = Object.keys(first as object)[0];
      return [
        `${pad}{`,
        `${pad}  name: ${quote(key)},`,
        `${pad}  title: ${title},`,
        `${pad}  type: 'array',`,
        `${pad}  of: [`,
        `${pad}    {`,
        `${pad}      type: 'object',`,
        `${pad}      name: ${quote(key.replace(/s$/, '') || 'item')},`,
        `${pad}      fields: [`,
        inner,
        `${pad}      ],`,
        `${pad}      preview: { select: { title: '${previewKey}.es' } },`,
        `${pad}    },`,
        `${pad}  ],`,
        `${pad}},`,
      ].join('\n');
    }
    return `${pad}{ name: ${quote(key)}, title: ${title}, type: 'array', of: [{ type: 'localeString' }] },`;
  }

  if (value && typeof value === 'object') {
    const inner = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => fieldFor(k, v, depth + 2))
      .join('\n');
    return [
      `${pad}{`,
      `${pad}  name: ${quote(key)},`,
      `${pad}  title: ${title},`,
      `${pad}  type: 'object',`,
      `${pad}  options: { collapsible: true, collapsed: true },`,
      `${pad}  fields: [`,
      inner,
      `${pad}  ],`,
      `${pad}},`,
    ].join('\n');
  }

  return `${pad}{ name: ${quote(key)}, title: ${title}, type: 'localeString' },`;
}

const sections = Object.entries(es);

const groups = sections
  .map(([k], i) => `    { name: ${quote(k)}, title: ${quote(titleCase(k))}${i === 0 ? ', default: true' : ''} },`)
  .join('\n');

const fields = sections
  .map(([key, value]) => {
    const body = fieldFor(key, value, 2).replace(/^ {4}\{/, '    defineField({').replace(/\},$/, '}),');
    return body.replace(`      name: ${quote(key)},`, `      name: ${quote(key)},\n      group: ${quote(key)},`);
  })
  .join('\n');

const out = `// AUTO-GENERATED by scripts/gen-sitecopy-schema.ts — do not edit by hand.
// Regenerate with: npm run sanity:gen-copy
import { defineField, defineType } from 'sanity';

/**
 * Every UI string on the site, mirroring the shape of \`src/config/dictionaries/es.ts\`.
 * A singleton: exactly one of these documents exists, id \`siteCopy\`.
 */
export const siteCopy = defineType({
  name: 'siteCopy',
  title: 'Textos del sitio',
  type: 'document',
  groups: [
${groups}
  ],
  fields: [
${fields}
  ],
  preview: { prepare: () => ({ title: 'Textos del sitio' }) },
});
`;

writeFileSync(OUT, out);

const leafCount = JSON.stringify(es).match(/"/g)!.length;
console.log(`Wrote ${OUT}`);
console.log(`  ${sections.length} sections, ~${leafCount} tokens of source copy mirrored`);
